version: "3"
services:
  todolist-mariadb:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: todolist
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
  todos-app:
    image: todos
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - todolist-mariadb
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://todolist-mariadb:3306/todolist'